/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/mac.sv:1.1-19.10" *)
module mac(a, b, acc, result);
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:198.20-198.21" *)
  wire [15:0] _000_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:198.23-198.24" *)
  wire [15:0] _001_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:198.26-198.27" *)
  wire [15:0] _002_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _003_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _004_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _005_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _006_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _007_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:198.20-198.21" *)
  wire [15:0] _008_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:198.23-198.24" *)
  wire [15:0] _009_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:198.26-198.27" *)
  wire [15:0] _010_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _011_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _012_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _013_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _014_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _016_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _019_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:198.23-198.24" *)
  wire [15:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:198.26-198.27" *)
  wire [15:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _026_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _027_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _029_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "15" *)
  wire [15:0] _038_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [15:0] _039_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [15:0] _040_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "15" *)
  wire [15:0] _041_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [15:0] _042_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  (* unused_bits = "15" *)
  wire [15:0] _043_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _044_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _045_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _046_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _047_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _048_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _049_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _050_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _051_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _052_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _053_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _054_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _055_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _056_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _057_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _058_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _059_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _060_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _061_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _062_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _063_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _064_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _065_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _066_;
  (* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _067_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _068_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _069_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _070_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _071_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _072_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _073_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _074_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _075_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _076_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _077_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _078_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _079_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _080_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _081_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _082_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _083_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _084_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _085_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _086_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _087_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _088_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _089_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _090_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _091_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _092_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _093_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _094_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _095_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _096_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _097_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _098_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _099_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _100_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _101_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _102_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _103_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _104_;
  (* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _105_;
  (* src = "rtl/mac.sv:4.30-4.31" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "rtl/mac.sv:6.32-6.35" *)
  input [15:0] acc;
  wire [15:0] acc;
  (* src = "rtl/mac.sv:5.30-5.31" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "rtl/mac.sv:11.25-11.32" *)
  wire [15:0] product;
  (* src = "rtl/mac.sv:8.32-8.38" *)
  output [15:0] result;
  wire [15:0] result;
  assign _080_ = _042_[5] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _042_[4];
  assign _081_ = _042_[7] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _042_[6];
  assign _082_ = _042_[9] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _042_[8];
  assign _083_ = _042_[11] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _042_[10];
  assign _084_ = _042_[13] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _042_[12];
  assign _085_ = _081_ &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _080_;
  assign _086_ = _083_ &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _082_;
  assign _087_ = _086_ &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _041_[7];
  assign _088_ = _080_ &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _041_[3];
  assign _089_ = _082_ &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _041_[7];
  assign _090_ = _084_ &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _041_[11];
  assign _091_ = _042_[2] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _041_[1];
  assign _092_ = _042_[4] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _041_[3];
  assign _093_ = _042_[6] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _041_[5];
  assign _094_ = _042_[8] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _041_[7];
  assign _095_ = _042_[10] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _041_[9];
  assign _096_ = _042_[12] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _041_[11];
  assign _097_ = _042_[14] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _041_[13];
  assign _041_[1] = _043_[1] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _068_;
  assign _098_ = _043_[3] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _069_;
  assign _099_ = _043_[5] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _070_;
  assign _100_ = _043_[7] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _071_;
  assign _101_ = _043_[9] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _072_;
  assign _102_ = _043_[11] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _073_;
  assign _103_ = _043_[13] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _074_;
  assign _041_[3] = _098_ |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _075_;
  assign _104_ = _100_ |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _076_;
  assign _105_ = _102_ |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _077_;
  assign _041_[7] = _104_ |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _078_;
  assign _041_[11] = _105_ |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _087_;
  assign _041_[5] = _099_ |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _088_;
  assign _041_[9] = _101_ |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _089_;
  assign _041_[13] = _103_ |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _090_;
  assign _041_[2] = _043_[2] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _091_;
  assign _041_[4] = _043_[4] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _092_;
  assign _041_[6] = _043_[6] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _093_;
  assign _041_[8] = _043_[8] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _094_;
  assign _041_[10] = _043_[10] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _095_;
  assign _041_[12] = _043_[12] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _096_;
  assign _041_[14] = _043_[14] |(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _097_;
  assign _044_ = _039_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _040_[6];
  assign _045_ = _039_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _040_[8];
  assign _046_ = _039_[11] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _040_[10];
  assign _047_ = _039_[13] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _040_[12];
  assign _048_ = _050_ &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _038_[5];
  assign _049_ = _052_ &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _064_;
  assign _050_ = _039_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[6];
  assign _051_ = _039_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[8];
  assign _052_ = _039_[11] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[10];
  assign _053_ = _039_[13] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[12];
  assign _054_ = _052_ &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _051_;
  assign _055_ = _054_ &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[7];
  assign _056_ = _051_ &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[7];
  assign _057_ = _053_ &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[11];
  assign _058_ = _039_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[5];
  assign _059_ = _039_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[7];
  assign _060_ = _039_[10] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[9];
  assign _061_ = _039_[12] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[11];
  assign _062_ = _039_[14] &(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[13];
  assign _063_ = _040_[7] |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _044_;
  assign _064_ = _040_[9] |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _045_;
  assign _065_ = _040_[11] |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _046_;
  assign _066_ = _040_[13] |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _047_;
  assign _038_[7] = _063_ |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _048_;
  assign _067_ = _065_ |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _049_;
  assign _038_[11] = _067_ |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _055_;
  assign _038_[9] = _064_ |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _056_;
  assign _038_[13] = _066_ |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _057_;
  assign _038_[6] = _040_[6] |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _058_;
  assign _038_[8] = _040_[8] |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _059_;
  assign _038_[10] = _040_[10] |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _060_;
  assign _038_[12] = _040_[12] |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _061_;
  assign _038_[14] = _040_[14] |(* src = "/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _062_;
  assign _000_[1] = a[0] & b[1];
  assign _000_[2] = a[1] & b[1];
  assign _000_[3] = a[2] & b[1];
  assign _000_[4] = a[3] & b[1];
  assign _000_[5] = a[4] & b[1];
  assign _000_[6] = a[5] & b[1];
  assign _000_[7] = a[6] & b[1];
  assign _000_[8] = a[7] & b[1];
  assign product[0] = a[0] & b[0];
  assign _001_[1] = a[1] & b[0];
  assign _001_[2] = a[2] & b[0];
  assign _001_[3] = a[3] & b[0];
  assign _001_[4] = a[4] & b[0];
  assign _001_[5] = a[5] & b[0];
  assign _001_[6] = a[6] & b[0];
  assign _001_[7] = a[7] & b[0];
  assign _002_[2] = a[0] & b[2];
  assign _002_[3] = a[1] & b[2];
  assign _002_[4] = a[2] & b[2];
  assign _002_[5] = a[3] & b[2];
  assign _002_[6] = a[4] & b[2];
  assign _002_[7] = a[5] & b[2];
  assign _002_[8] = a[6] & b[2];
  assign _002_[9] = a[7] & b[2];
  assign _008_[3] = a[0] & b[3];
  assign _008_[4] = a[1] & b[3];
  assign _008_[5] = a[2] & b[3];
  assign _008_[6] = a[3] & b[3];
  assign _008_[7] = a[4] & b[3];
  assign _008_[8] = a[5] & b[3];
  assign _008_[9] = a[6] & b[3];
  assign _008_[10] = a[7] & b[3];
  assign _009_[4] = a[0] & b[4];
  assign _009_[5] = a[1] & b[4];
  assign _009_[6] = a[2] & b[4];
  assign _009_[7] = a[3] & b[4];
  assign _009_[8] = a[4] & b[4];
  assign _009_[9] = a[5] & b[4];
  assign _009_[10] = a[6] & b[4];
  assign _009_[11] = a[7] & b[4];
  assign _010_[5] = a[0] & b[5];
  assign _010_[6] = a[1] & b[5];
  assign _010_[7] = a[2] & b[5];
  assign _010_[8] = a[3] & b[5];
  assign _010_[9] = a[4] & b[5];
  assign _010_[10] = a[5] & b[5];
  assign _010_[11] = a[6] & b[5];
  assign _010_[12] = a[7] & b[5];
  assign _021_[6] = a[0] & b[6];
  assign _021_[7] = a[1] & b[6];
  assign _021_[8] = a[2] & b[6];
  assign _021_[9] = a[3] & b[6];
  assign _021_[10] = a[4] & b[6];
  assign _021_[11] = a[5] & b[6];
  assign _021_[12] = a[6] & b[6];
  assign _021_[13] = a[7] & b[6];
  assign _022_[7] = a[0] & b[7];
  assign _022_[8] = a[1] & b[7];
  assign _022_[9] = a[2] & b[7];
  assign _022_[10] = a[3] & b[7];
  assign _022_[11] = a[4] & b[7];
  assign _022_[12] = a[5] & b[7];
  assign _022_[13] = a[6] & b[7];
  assign _022_[14] = a[7] & b[7];
  assign result[1] = _042_[1] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[0];
  assign result[2] = _042_[2] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[1];
  assign result[3] = _042_[3] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[2];
  assign result[4] = _042_[4] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[3];
  assign result[5] = _042_[5] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[4];
  assign result[6] = _042_[6] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[5];
  assign result[7] = _042_[7] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[6];
  assign result[8] = _042_[8] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[7];
  assign result[9] = _042_[9] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[8];
  assign result[10] = _042_[10] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[9];
  assign result[11] = _042_[11] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[10];
  assign result[12] = _042_[12] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[11];
  assign result[13] = _042_[13] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[12];
  assign result[14] = _042_[14] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[13];
  assign result[15] = _042_[15] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _041_[14];
  assign result[0] = acc[0] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[0];
  assign _042_[1] = acc[1] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[1];
  assign _042_[2] = acc[2] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[2];
  assign _042_[3] = acc[3] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[3];
  assign _042_[4] = acc[4] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[4];
  assign _042_[5] = acc[5] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[5];
  assign _042_[6] = acc[6] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[6];
  assign _042_[7] = acc[7] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[7];
  assign _042_[8] = acc[8] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[8];
  assign _042_[9] = acc[9] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[9];
  assign _042_[10] = acc[10] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[10];
  assign _042_[11] = acc[11] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[11];
  assign _042_[12] = acc[12] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[12];
  assign _042_[13] = acc[13] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[13];
  assign _042_[14] = acc[14] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[14];
  assign _042_[15] = acc[15] ^(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  product[15];
  assign _041_[0] = acc[0] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[0];
  assign _043_[1] = acc[1] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[1];
  assign _043_[2] = acc[2] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[2];
  assign _043_[3] = acc[3] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[3];
  assign _043_[4] = acc[4] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[4];
  assign _043_[5] = acc[5] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[5];
  assign _043_[6] = acc[6] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[6];
  assign _043_[7] = acc[7] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[7];
  assign _043_[8] = acc[8] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[8];
  assign _043_[9] = acc[9] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[9];
  assign _043_[10] = acc[10] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[10];
  assign _043_[11] = acc[11] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[11];
  assign _043_[12] = acc[12] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[12];
  assign _043_[13] = acc[13] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[13];
  assign _043_[14] = acc[14] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  product[14];
  assign _003_[2] = _006_[2] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[2];
  assign _003_[3] = _006_[3] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[3];
  assign _003_[4] = _006_[4] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[4];
  assign _003_[5] = _006_[5] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[5];
  assign _003_[6] = _006_[6] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[6];
  assign _003_[7] = _006_[7] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[7];
  assign _004_[2] = _005_[2] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[2];
  assign _004_[3] = _005_[3] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[3];
  assign _004_[4] = _005_[4] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[4];
  assign _004_[5] = _005_[5] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[5];
  assign _004_[6] = _005_[6] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[6];
  assign _004_[7] = _005_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[7];
  assign _004_[8] = _000_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[8];
  assign _007_[2] = _002_[2] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[2];
  assign _007_[3] = _002_[3] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[3];
  assign _007_[4] = _002_[4] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[4];
  assign _007_[5] = _002_[5] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[5];
  assign _007_[6] = _002_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[6];
  assign _007_[7] = _002_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[7];
  assign _003_[8] = _002_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _000_[8];
  assign _003_[1] = _000_[1] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[1];
  assign _006_[2] = _000_[2] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[2];
  assign _006_[3] = _000_[3] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[3];
  assign _006_[4] = _000_[4] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[4];
  assign _006_[5] = _000_[5] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[5];
  assign _006_[6] = _000_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[6];
  assign _006_[7] = _000_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[7];
  assign product[1] = _000_[1] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[1];
  assign _005_[2] = _000_[2] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[2];
  assign _005_[3] = _000_[3] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[3];
  assign _005_[4] = _000_[4] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[4];
  assign _005_[5] = _000_[5] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[5];
  assign _005_[6] = _000_[6] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[6];
  assign _005_[7] = _000_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[7];
  assign _011_[5] = _014_[5] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[5];
  assign _011_[6] = _014_[6] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[6];
  assign _011_[7] = _014_[7] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[7];
  assign _011_[8] = _014_[8] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[8];
  assign _011_[9] = _014_[9] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[9];
  assign _011_[10] = _014_[10] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[10];
  assign _012_[5] = _013_[5] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[5];
  assign _012_[6] = _013_[6] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[6];
  assign _012_[7] = _013_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[7];
  assign _012_[8] = _013_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[8];
  assign _012_[9] = _013_[9] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[9];
  assign _012_[10] = _013_[10] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[10];
  assign _012_[11] = _009_[11] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[11];
  assign _015_[5] = _010_[5] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[5];
  assign _015_[6] = _010_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[6];
  assign _015_[7] = _010_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[7];
  assign _015_[8] = _010_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[8];
  assign _015_[9] = _010_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[9];
  assign _015_[10] = _010_[10] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[10];
  assign _011_[11] = _010_[11] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _009_[11];
  assign _011_[4] = _008_[4] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[4];
  assign _014_[5] = _008_[5] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[5];
  assign _014_[6] = _008_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[6];
  assign _014_[7] = _008_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[7];
  assign _014_[8] = _008_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[8];
  assign _014_[9] = _008_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[9];
  assign _014_[10] = _008_[10] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[10];
  assign _012_[4] = _008_[4] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[4];
  assign _013_[5] = _008_[5] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[5];
  assign _013_[6] = _008_[6] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[6];
  assign _013_[7] = _008_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[7];
  assign _013_[8] = _008_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[8];
  assign _013_[9] = _008_[9] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[9];
  assign _013_[10] = _008_[10] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[10];
  assign _016_[3] = _019_[3] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[3];
  assign _016_[4] = _019_[4] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[4];
  assign _016_[5] = _019_[5] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[5];
  assign _016_[6] = _019_[6] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[6];
  assign _016_[7] = _019_[7] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[7];
  assign _016_[8] = _019_[8] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[8];
  assign _016_[9] = _019_[9] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[9];
  assign _017_[3] = _018_[3] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _008_[3];
  assign _017_[4] = _018_[4] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[4];
  assign _017_[5] = _018_[5] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[5];
  assign _017_[6] = _018_[6] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[6];
  assign _017_[7] = _018_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[7];
  assign _017_[8] = _018_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[8];
  assign _017_[9] = _018_[9] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[9];
  assign _020_[3] = _008_[3] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[3];
  assign _020_[4] = _012_[4] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[4];
  assign _020_[5] = _012_[5] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[5];
  assign _020_[6] = _012_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[6];
  assign _020_[7] = _012_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[7];
  assign _020_[8] = _012_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[8];
  assign _020_[9] = _012_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[9];
  assign _016_[2] = _004_[2] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[1];
  assign _019_[3] = _004_[3] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[2];
  assign _019_[4] = _004_[4] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[3];
  assign _019_[5] = _004_[5] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[4];
  assign _019_[6] = _004_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[5];
  assign _019_[7] = _004_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[6];
  assign _019_[8] = _004_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[7];
  assign _019_[9] = _002_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[8];
  assign product[2] = _004_[2] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[1];
  assign _018_[3] = _004_[3] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[2];
  assign _018_[4] = _004_[4] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[3];
  assign _018_[5] = _004_[5] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[4];
  assign _018_[6] = _004_[6] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[5];
  assign _018_[7] = _004_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[6];
  assign _018_[8] = _004_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[7];
  assign _018_[9] = _002_[9] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[8];
  assign _023_[7] = _026_[7] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[7];
  assign _023_[8] = _026_[8] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[8];
  assign _023_[9] = _026_[9] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[9];
  assign _023_[10] = _026_[10] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[10];
  assign _023_[11] = _026_[11] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[11];
  assign _023_[12] = _026_[12] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[12];
  assign _024_[7] = _025_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[7];
  assign _024_[8] = _025_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[8];
  assign _024_[9] = _025_[9] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[9];
  assign _024_[10] = _025_[10] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[10];
  assign _024_[11] = _025_[11] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[11];
  assign _024_[12] = _025_[12] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[12];
  assign _024_[13] = _021_[13] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[13];
  assign _027_[7] = _022_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[7];
  assign _027_[8] = _022_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[8];
  assign _027_[9] = _022_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[9];
  assign _027_[10] = _022_[10] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[10];
  assign _027_[11] = _022_[11] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[11];
  assign _027_[12] = _022_[12] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[12];
  assign _023_[13] = _022_[13] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _021_[13];
  assign _023_[6] = _011_[5] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[6];
  assign _026_[7] = _011_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[7];
  assign _026_[8] = _011_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[8];
  assign _026_[9] = _011_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[9];
  assign _026_[10] = _011_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[10];
  assign _026_[11] = _011_[10] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[11];
  assign _026_[12] = _011_[11] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[12];
  assign _024_[6] = _011_[5] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[6];
  assign _025_[7] = _011_[6] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[7];
  assign _025_[8] = _011_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[8];
  assign _025_[9] = _011_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[9];
  assign _025_[10] = _011_[9] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[10];
  assign _025_[11] = _011_[10] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[11];
  assign _025_[12] = _011_[11] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[12];
  assign _028_[5] = _031_[5] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[5];
  assign _028_[6] = _031_[6] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[6];
  assign _028_[7] = _031_[7] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[7];
  assign _028_[8] = _031_[8] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[8];
  assign _028_[9] = _031_[9] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[9];
  assign _028_[10] = _031_[10] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[10];
  assign _029_[5] = _030_[5] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _011_[4];
  assign _029_[6] = _030_[6] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[6];
  assign _029_[7] = _030_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[7];
  assign _029_[8] = _030_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[8];
  assign _029_[9] = _030_[9] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[9];
  assign _029_[10] = _030_[10] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[10];
  assign _029_[11] = _012_[11] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[11];
  assign _029_[12] = _010_[12] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[12];
  assign _032_[5] = _011_[4] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[5];
  assign _032_[6] = _024_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[6];
  assign _032_[7] = _024_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[7];
  assign _032_[8] = _024_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[8];
  assign _032_[9] = _024_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[9];
  assign _032_[10] = _024_[10] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[10];
  assign _028_[11] = _024_[11] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _012_[11];
  assign _028_[12] = _024_[12] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _010_[12];
  assign _028_[3] = _017_[3] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[2];
  assign _028_[4] = _017_[4] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[3];
  assign _031_[5] = _017_[5] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[4];
  assign _031_[6] = _017_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[5];
  assign _031_[7] = _017_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[6];
  assign _031_[8] = _017_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[7];
  assign _031_[9] = _017_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[8];
  assign _031_[10] = _012_[10] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[9];
  assign product[3] = _017_[3] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[2];
  assign _029_[4] = _017_[4] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[3];
  assign _030_[5] = _017_[5] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[4];
  assign _030_[6] = _017_[6] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[5];
  assign _030_[7] = _017_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[6];
  assign _030_[8] = _017_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[7];
  assign _030_[9] = _017_[9] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[8];
  assign _030_[10] = _012_[10] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[9];
  assign _033_[7] = _036_[7] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[7];
  assign _033_[8] = _036_[8] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[8];
  assign _033_[9] = _036_[9] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[9];
  assign _033_[10] = _036_[10] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[10];
  assign _033_[11] = _036_[11] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[11];
  assign _033_[12] = _036_[12] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[12];
  assign _033_[13] = _036_[13] |(* src = "/usr/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[13];
  assign _034_[7] = _035_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[6];
  assign _034_[8] = _035_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[7];
  assign _034_[9] = _035_[9] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[8];
  assign _034_[10] = _035_[10] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[9];
  assign _034_[11] = _035_[11] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[10];
  assign _034_[12] = _035_[12] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[11];
  assign _034_[13] = _035_[13] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[12];
  assign _034_[14] = _022_[14] ^(* src = "/usr/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[13];
  assign _037_[7] = _023_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[7];
  assign _037_[8] = _023_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[8];
  assign _037_[9] = _023_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[9];
  assign _037_[10] = _023_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[10];
  assign _037_[11] = _023_[10] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[11];
  assign _037_[12] = _023_[11] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[12];
  assign _037_[13] = _023_[12] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[13];
  assign _033_[14] = _023_[13] &(* src = "/usr/bin/../share/yosys/techmap.v:205.38-205.44" *)  _022_[14];
  assign _033_[4] = _029_[4] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[3];
  assign _033_[5] = _029_[5] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[4];
  assign _033_[6] = _029_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[5];
  assign _036_[7] = _029_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[6];
  assign _036_[8] = _029_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[7];
  assign _036_[9] = _029_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[8];
  assign _036_[10] = _029_[10] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[9];
  assign _036_[11] = _029_[11] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[10];
  assign _036_[12] = _029_[12] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[11];
  assign _036_[13] = _024_[13] &(* src = "/usr/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[12];
  assign product[4] = _029_[4] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[3];
  assign _034_[5] = _029_[5] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[4];
  assign _034_[6] = _029_[6] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[5];
  assign _035_[7] = _029_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[6];
  assign _035_[8] = _029_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[7];
  assign _035_[9] = _029_[9] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[8];
  assign _035_[10] = _029_[10] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[9];
  assign _035_[11] = _029_[11] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[10];
  assign _035_[12] = _029_[12] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[11];
  assign _035_[13] = _024_[13] ^(* src = "/usr/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[12];
  assign product[6] = _039_[6] ^(* src = "/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _038_[5];
  assign product[7] = _039_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _038_[6];
  assign product[8] = _039_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _038_[7];
  assign product[9] = _039_[9] ^(* src = "/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _038_[8];
  assign product[10] = _039_[10] ^(* src = "/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _038_[9];
  assign product[11] = _039_[11] ^(* src = "/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _038_[10];
  assign product[12] = _039_[12] ^(* src = "/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _038_[11];
  assign product[13] = _039_[13] ^(* src = "/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _038_[12];
  assign product[14] = _039_[14] ^(* src = "/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _038_[13];
  assign product[15] = _033_[14] ^(* src = "/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _038_[14];
  assign product[5] = _034_[5] ^(* src = "/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _033_[4];
  assign _039_[6] = _034_[6] ^(* src = "/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _033_[5];
  assign _039_[7] = _034_[7] ^(* src = "/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _033_[6];
  assign _039_[8] = _034_[8] ^(* src = "/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _033_[7];
  assign _039_[9] = _034_[9] ^(* src = "/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _033_[8];
  assign _039_[10] = _034_[10] ^(* src = "/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _033_[9];
  assign _039_[11] = _034_[11] ^(* src = "/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _033_[10];
  assign _039_[12] = _034_[12] ^(* src = "/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _033_[11];
  assign _039_[13] = _034_[13] ^(* src = "/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _033_[12];
  assign _039_[14] = _034_[14] ^(* src = "/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _033_[13];
  assign _038_[5] = _034_[5] &(* src = "/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _033_[4];
  assign _040_[6] = _034_[6] &(* src = "/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _033_[5];
  assign _040_[7] = _034_[7] &(* src = "/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _033_[6];
  assign _040_[8] = _034_[8] &(* src = "/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _033_[7];
  assign _040_[9] = _034_[9] &(* src = "/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _033_[8];
  assign _040_[10] = _034_[10] &(* src = "/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _033_[9];
  assign _040_[11] = _034_[11] &(* src = "/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _033_[10];
  assign _040_[12] = _034_[12] &(* src = "/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _033_[11];
  assign _040_[13] = _034_[13] &(* src = "/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _033_[12];
  assign _040_[14] = _034_[14] &(* src = "/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _033_[13];
  assign _068_ = _042_[1] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_[0];
  assign _069_ = _042_[3] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _043_[2];
  assign _070_ = _042_[5] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _043_[4];
  assign _071_ = _042_[7] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _043_[6];
  assign _072_ = _042_[9] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _043_[8];
  assign _073_ = _042_[11] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _043_[10];
  assign _074_ = _042_[13] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _043_[12];
  assign _075_ = _079_ &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_[1];
  assign _076_ = _081_ &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _099_;
  assign _077_ = _083_ &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _101_;
  assign _078_ = _085_ &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_[3];
  assign _079_ = _042_[3] &(* src = "rtl/mac.sv:17.21-17.34|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _042_[2];
  assign { _000_[15:9], _000_[0] } = 8'h00;
  assign { _001_[15:8], _001_[0] } = { 8'h00, product[0] };
  assign { _002_[15:10], _002_[1:0] } = 8'h00;
  assign { _003_[15:9], _003_[0] } = 8'h00;
  assign { _004_[15:9], _004_[1:0] } = { 6'h00, _002_[9], product[1:0] };
  assign { _005_[15:8], _005_[1:0] } = { 7'h00, _000_[8], product[1:0] };
  assign { _006_[15:8], _006_[1:0] } = { 8'h00, _003_[1], 1'h0 };
  assign { _007_[15:8], _007_[1:0] } = { 7'h00, _003_[8], 2'h0 };
  assign { _008_[15:11], _008_[2:0] } = 8'h00;
  assign { _009_[15:12], _009_[3:0] } = 8'h00;
  assign { _010_[15:13], _010_[4:0] } = 8'h00;
  assign { _011_[15:12], _011_[3:0] } = 8'h00;
  assign { _012_[15:12], _012_[3:0] } = { 3'h0, _010_[12], _008_[3], 3'h0 };
  assign { _013_[15:11], _013_[4:0] } = { 4'h0, _009_[11], _012_[4], _008_[3], 3'h0 };
  assign { _014_[15:11], _014_[4:0] } = { 5'h00, _011_[4], 4'h0 };
  assign { _015_[15:11], _015_[4:0] } = { 4'h0, _011_[11], 5'h00 };
  assign { _016_[15:10], _016_[1:0] } = 8'h00;
  assign { _017_[15:10], _017_[2:0] } = { 3'h0, _010_[12], _012_[11:10], product[2:0] };
  assign { _018_[15:10], _018_[2:0] } = { 6'h00, product[2:0] };
  assign { _019_[15:10], _019_[2:0] } = { 6'h00, _016_[2], 2'h0 };
  assign { _020_[15:10], _020_[2:0] } = 9'h000;
  assign { _021_[15:14], _021_[5:0] } = 8'h00;
  assign { _022_[15], _022_[6:0] } = 8'h00;
  assign { _023_[15:14], _023_[5:0] } = 8'h00;
  assign { _024_[15:14], _024_[5:0] } = { 1'h0, _022_[14], _011_[4], 5'h00 };
  assign { _025_[15:13], _025_[6:0] } = { 2'h0, _021_[13], _024_[6], _011_[4], 5'h00 };
  assign { _026_[15:13], _026_[6:0] } = { 3'h0, _023_[6], 6'h00 };
  assign { _027_[15:13], _027_[6:0] } = { 2'h0, _023_[13], 7'h00 };
  assign { _028_[15:13], _028_[2:0] } = 6'h00;
  assign { _029_[15:13], _029_[3:0] } = { 1'h0, _022_[14], _024_[13], product[3:0] };
  assign { _030_[15:11], _030_[4:0] } = { 3'h0, _010_[12], _012_[11], _029_[4], product[3:0] };
  assign { _031_[15:11], _031_[4:0] } = { 5'h00, _028_[4:3], 3'h0 };
  assign { _032_[15:11], _032_[4:0] } = { 3'h0, _028_[12:11], 5'h00 };
  assign { _033_[15], _033_[3:0] } = 5'h00;
  assign { _034_[15], _034_[4:0] } = { 1'h0, product[4:0] };
  assign { _035_[15:14], _035_[6:0] } = { 1'h0, _022_[14], _034_[6:5], product[4:0] };
  assign { _036_[15:14], _036_[6:0] } = { 2'h0, _033_[6:4], 4'h0 };
  assign { _037_[15:14], _037_[6:0] } = { 1'h0, _033_[14], 7'h00 };
  assign _038_[4:0] = 5'h00;
  assign { _039_[15], _039_[5:0] } = { _033_[14], product[5:0] };
  assign { _040_[15], _040_[5:0] } = { 1'h0, _038_[5], 5'h00 };
  assign _042_[0] = result[0];
  assign _043_[0] = _041_[0];
endmodule
